//! Wire-format types shared by every node kind.
//!
//! `Gossip` is one logical Lightning gossip message — a channel update,
//! announcement, etc. The protocol details aren't modelled here; we only
//! track an opaque ID for dedup and a byte-size for future bandwidth
//! accounting.
//!
//! `WireMessage` is what actually flows on the wire between models. It
//! has two variants:
//! * `Single(Gossip)` — used by flooding and by all originations.
//! * `Batch(Vec<Gossip>)` — used by stagger algorithms (CLN/LND) that
//!   coalesce multiple gossips into one transmission per tick.
//!
//! Receivers iterate `.iter_gossips()` and process each inner gossip
//! identically. Having one shared wire enum (rather than per-algorithm
//! types) is what lets a CLN node forward a `Batch` to an LND peer in a
//! mixed population — both nodes' `recv` ports take `WireMessage`.

use std::sync::Arc;

use serde::{Deserialize, Serialize};

/// Stable node identifier. For synthetic configs, this is the dense
/// 0..n insertion order cast to u64. For CSV-loaded configs, it's
/// `xxhash64(seed, pubkey)`. We use u64 so the hash space is wide
/// enough that birthday-collision probability stays negligible on
/// real LN datasets (~12k nodes / ~42k channels).
pub type NodeId = u64;
/// Per-origination ID; unique across all events generated by an event
/// stream. 32 bits = 4 G distinct messages, plenty for any realistic run.
pub type MsgId = u32;
/// Stand-in for a BOLT 7 short-channel-id. u64 because real SCIDs are
/// 64-bit, and because xxhash64 of the SCID string for CSV loading
/// is the cleanest collision-free representation.
pub type Scid = u64;
/// Stand-in for the channel-direction bit (BOLT 7 `channel_flags` bit 0).
/// Always 0 or 1.
pub type Direction = u8;
/// Dense per-node index used for `Vec`-indexed storage (e.g. metrics'
/// per-MsgId coverage vector). Always in `0..n_nodes` and equal to
/// `petgraph::NodeIndex::index()` on the topology peer graph. Distinct
/// from `NodeId`, which can be sparse u64 from a CSV hash.
pub type NodeIdx = u32;

#[derive(Copy, Clone, Debug, Serialize, Deserialize)]
pub struct Gossip {
    pub id: MsgId,
    pub origin: NodeId,
    pub kind: GossipKind,
    /// On-the-wire size, used for bandwidth metrics. Real BOLT 7
    /// gossip messages cap around 1364 bytes (`node_announcement` with
    /// max addresses); `u16` gives 64 KiB of headroom and shrinks the
    /// `Gossip` struct slightly.
    pub size_bytes: u16,
    /// Short channel ID. Meaningful for `ChannelAnnouncement` and
    /// `ChannelUpdate`; ignored for `NodeAnnouncement` (set to 0).
    pub scid: Scid,
    /// Which side of the channel this update represents (0 or 1).
    /// Meaningful for `ChannelUpdate`; ignored for the other kinds
    /// (set to 0).
    pub direction: Direction,
    /// Seconds since `MonotonicTime::EPOCH`. Set to 0 by event-stream
    /// generators; populated by the originating node's `originate`
    /// handler at the moment of broadcast for `ChannelUpdate` and
    /// `NodeAnnouncement` (matches BOLT 7's "node sets timestamp on
    /// send"). For `ChannelAnnouncement` the timestamp field is
    /// unused — channel announcements are not timestamped in BOLT 7.
    /// 32 bits = ~136 years of seconds — far longer than any sim run.
    pub timestamp: u32,
}

/// The three BOLT 7 gossip message kinds the simulator distinguishes.
/// Dedup semantics differ per kind:
///
/// * `NodeAnnouncement`: keyed on `(origin, timestamp)`; highest
///   timestamp seen per origin wins.
/// * `ChannelAnnouncement`: keyed on `scid` alone; first seen wins
///   (no timestamp in real BOLT 7).
/// * `ChannelUpdate`: keyed on `(scid, direction, timestamp)`; highest
///   timestamp per `(scid, direction)` wins.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum GossipKind {
    NodeAnnouncement,
    ChannelAnnouncement,
    ChannelUpdate,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum WireMessage {
    Single(Gossip),
    /// Stagger-tick payload, immutable after construction. `Arc` so
    /// NeXosim's per-recipient broadcast clone is a refcount bump
    /// instead of an O(batch_len) `Vec` copy.
    Batch(Arc<Vec<Gossip>>),
}

impl WireMessage {
    /// Iterate over the inner `Gossip`s regardless of variant. Receivers
    /// don't need to care whether they got one message or a hundred.
    pub fn iter_gossips(&self) -> Box<dyn Iterator<Item = &Gossip> + '_> {
        match self {
            WireMessage::Single(g) => Box::new(std::iter::once(g)),
            WireMessage::Batch(v) => Box::new(v.iter()),
        }
    }
}
