//! Wire-format types shared by every node kind.
//!
//! `Gossip` is one logical Lightning gossip message — a channel update,
//! announcement, etc. The protocol details aren't modelled here; we only
//! track an opaque ID for dedup and a byte-size for future bandwidth
//! accounting.
//!
//! `WireMessage` is what actually flows on the wire between models. It
//! has two variants:
//! * `Single(Gossip)` — used by flooding and by all originations.
//! * `Batch(Vec<Gossip>)` — used by stagger algorithms (CLN/LND) that
//!   coalesce multiple gossips into one transmission per tick.
//!
//! Receivers iterate `.iter_gossips()` and process each inner gossip
//! identically. Having one shared wire enum (rather than per-algorithm
//! types) is what lets a CLN node forward a `Batch` to an LND peer in a
//! mixed population — both nodes' `recv` ports take `WireMessage`.

use serde::{Deserialize, Serialize};

pub type NodeId = u32;
/// Per-origination ID; unique across all events generated by an event
/// stream. 32 bits = 4 G distinct messages, plenty for any realistic run.
pub type MsgId = u32;
/// Stand-in for a BOLT 7 short-channel-id. 32 bits = 4 G channels,
/// plenty even for synthetic stress runs.
pub type Scid = u32;
/// Stand-in for the channel-direction bit (BOLT 7 `channel_flags` bit 0).
/// Always 0 or 1.
pub type Direction = u8;

#[derive(Copy, Clone, Debug, Serialize, Deserialize)]
pub struct Gossip {
    pub id: MsgId,
    pub origin: NodeId,
    pub kind: GossipKind,
    /// On-the-wire size, used for bandwidth metrics (not yet wired up).
    pub size_bytes: u32,
    /// Short channel ID this update is for.
    pub scid: Scid,
    /// Which side of the channel this update represents (0 or 1).
    pub direction: Direction,
    /// Seconds since `MonotonicTime::EPOCH`. Set to 0 by event-stream
    /// generators; populated by the originating node's `originate`
    /// handler at the moment of broadcast (matches BOLT 7's "node sets
    /// timestamp on send"). 32 bits = ~136 years of seconds — far longer
    /// than any sim run.
    pub timestamp: u32,
}

/// Future-extension point for inventory entries / reconciliation
/// payloads. Currently every gossip is a `Full` message.
#[derive(Copy, Clone, Debug, Serialize, Deserialize)]
pub enum GossipKind {
    Full,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum WireMessage {
    Single(Gossip),
    Batch(Vec<Gossip>),
}

impl WireMessage {
    /// Iterate over the inner `Gossip`s regardless of variant. Receivers
    /// don't need to care whether they got one message or a hundred.
    pub fn iter_gossips(&self) -> Box<dyn Iterator<Item = &Gossip> + '_> {
        match self {
            WireMessage::Single(g) => Box::new(std::iter::once(g)),
            WireMessage::Batch(v) => Box::new(v.iter()),
        }
    }
}
